// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSO-WYQtPgljibAu_3_BNttzhCyVhVKqE',
    appId: '1:828889639889:web:70a466a12477911dfd4ef0',
    messagingSenderId: '828889639889',
    projectId: 'registration-backend-f81ba',
    authDomain: 'registration-backend-f81ba.firebaseapp.com',
    storageBucket: 'registration-backend-f81ba.firebasestorage.app',
    measurementId: 'G-HJGT85QYNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuCecnXNmhg726uU6UTfICoTS2UDl2VV0',
    appId: '1:828889639889:android:a6e3f3d2c5bb61b1fd4ef0',
    messagingSenderId: '828889639889',
    projectId: 'registration-backend-f81ba',
    storageBucket: 'registration-backend-f81ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATAZ6y5DBGxFzikaR9Boxvbuj7IPBS7TU',
    appId: '1:828889639889:ios:7b172829014d79c6fd4ef0',
    messagingSenderId: '828889639889',
    projectId: 'registration-backend-f81ba',
    storageBucket: 'registration-backend-f81ba.firebasestorage.app',
    iosBundleId: 'com.example.resigrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATAZ6y5DBGxFzikaR9Boxvbuj7IPBS7TU',
    appId: '1:828889639889:ios:7b172829014d79c6fd4ef0',
    messagingSenderId: '828889639889',
    projectId: 'registration-backend-f81ba',
    storageBucket: 'registration-backend-f81ba.firebasestorage.app',
    iosBundleId: 'com.example.resigrationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSO-WYQtPgljibAu_3_BNttzhCyVhVKqE',
    appId: '1:828889639889:web:e7c738d76eb1f216fd4ef0',
    messagingSenderId: '828889639889',
    projectId: 'registration-backend-f81ba',
    authDomain: 'registration-backend-f81ba.firebaseapp.com',
    storageBucket: 'registration-backend-f81ba.firebasestorage.app',
    measurementId: 'G-28WW82NB4Q',
  );
}
